platform:
  accel: "gpu"
  cache_dir: "/kaggle"
  thermompnn_dir: "/kaggle/working/ThermoMPNN"
  embeddings_dir: "/kaggle/working/ThermoMPNN/embeddings"

data_loc:
        megascale_csv: "/kaggle/input/tsuboyama2023-dataset2-dataset3-20230416-csv/Tsuboyama2023_Dataset2_Dataset3_20230416.csv"
        megascale_splits: "dataset_splits/mega_splits.pkl"
        megascale_pdbs: "mega_scale/AlphaFold_model_PDBs"

        fireprot_csv: "fireprot_upload/csvs/4_fireprotDB_bestpH.csv"
        fireprot_splits: "fireprot_upload/csvs/fireprot_splits.pkl"
        fireprot_pdbs: "fireprot_upload/pdbs"